### ISSUE TITLE
Syntax file loading error when the syntax is auto recognized from text

### ISSUE THREAD

**Issue by ghost** [heyglen/network_tech#12]
# Which Syntax?:
All the ones included in the Network tech package

# Expected behavior and actual behavior:
Opening Sublime Text and pasting a Cisco configuration in a blank file should result in the syntax type being auto recognized and the correct syntax selected. Instead, the following exception is thrown and a wrong syntax is displayed in the lower right corner of the window (Ex cisco-ios instead of Cisco IOS).
The syntax works perfectly if selected manually. I've already tried reinstalling Sublime Text from scratch

# Error dump
error: Error loading syntax file "Packages/network_tech/cisco-ios.sublime-syntax": Unable to read Packages/network_tech/cisco-ios.sublime-syntax
Traceback (most recent call last):
  File "C:\Users\Enrico Gasparini\OneDrive\Programmi\PortableApps\Sublime Text Portable\sublime_plugin.py", line 490, in run_async_view_listener_callback
    vel.__class__.__dict__[name](vel)
  File "C:\Users\Enrico Gasparini\OneDrive\Programmi\PortableApps\Sublime Text Portable\Data\Installed Packages\Network Tech.sublime-package\network_tech.py", line 236, in on_modified_async
    self.network_info()
  File "C:\Users\Enrico Gasparini\OneDrive\Programmi\PortableApps\Sublime Text Portable\Data\Installed Packages\Network Tech.sublime-package\network_tech.py", line 239, in network_info
    if not self.view.scope_name(point).startswith(SCOPE_PREFIX):
  File "C:\Users\Enrico Gasparini\OneDrive\Programmi\PortableApps\Sublime Text Portable\sublime.py", line 884, in scope_name
    return sublime_api.view_scope_name(self.view_id, pt)
TypeError: an integer is required (got type NoneType)

# Steps to reproduce the problem:
Install a new portable copy of Sublime Text 3 build 3176
Install package control and Network Tech
Create a new file
Paste a cisco IOS configuration in it
Error occours

# Attached files
Sample configuration causing the error : [Sample.txt](https://github.com/heyglen/network_tech/files/2009438/Sample.txt)
Zipped mp4 screencast of the error: [Error screencast.zip](https://github.com/heyglen/network_tech/files/2009446/Error.screencast.zip)

**Comment by heyglen** [comment]
Fixed in the latest version. Thank you for reporting :smiley:.

**Comment by ghost** [comment]
It seems that the problem is still present in version 2.14.0, at least for ACE, IOS and ASA.
NXOS seems to be working :)

**Comment by ghost** [comment]
@heyglen sorry, I don't find how to reopen the issue o:)

**Comment by heyglen** [comment]
@ilGaspa I forgot to commit the change in the last release! oops...

I've just pushed a new minor release with it included. Hope it works out this time.

Thanks again.
