### ISSUE TITLE
Network Find not working and mouse over IP info not working

### ISSUE THREAD

**Issue by jsakofsky** [heyglen/network_tech#18]
# Which Syntax?:
Cisco IOS
# Expected behavior and actual behavior:
No mouse over actions on IP addresses and no Network Find in command window
# Steps to reproduce the problem:

# New Feature Description:

# Example Syntax

# Link to command reference

Sublime Version:
startup, version: 3200 osx x64 channel: stable

Console output:
reloading plugin Network Tech.network_tech
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Network Tech.sublime-package/network_tech.py", line 10, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Network Tech.sublime-package/lib/search/network/__init__.py", line 3, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Network Tech.sublime-package/lib/search/network/listener.py", line 10, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Network Tech.sublime-package/lib/search/network/network.py", line 16, in <module>
ImportError: No module named 'network_tech'

**Comment by stevelemi** [comment]
i have the same.

**Comment by heyglen** [comment]
I just released a patch that should address this, please let me know how it goes.

Thanks for reporting!

**Comment by stevelemi** [comment]
Thank you so much for having a look at this. 

I know have v.2.24.3 and it is still not working. 
(btw. password decryption is also not working.)

**Comment by heyglen** [comment]
Hmmm... Any errors in the console?

Did you try restarting Sublime Text? There are some dependencies that require an app restart.

**Comment by heyglen** [comment]
ah nevermind... i can reproduce it now.

Will get back to you when I get more clever :sweat_smile:

**Comment by heyglen** [comment]
So now there is a version 2.24.7

The package name is "Network Tech" which is not a python import friendly name, so I had to do some import tricks to get it to work:

Modified:
* [lib/iana/iana.py](https://github.com/heyglen/network_tech/blob/8c73cbf1be11fdb9d1ccb0d3fabbfba415e80793/lib/iana/iana.py#L16)
* [lib/search/network/network.py](https://github.com/heyglen/network_tech/blob/8c73cbf1be11fdb9d1ccb0d3fabbfba415e80793/lib/search/network/network.py#L18)

**Comment by jsakofsky** [comment]
looks great, fixed for me. thanks for all the work and the quick fix! great project, looking fwd to using it more.
